rabbitmq:
  enabled: true
  image: rabbitmq
  tag: 3.12-management
  replicas: 1
  service:
    amqp:
      name: amqp 
      type: ClusterIP
      port: 5672
    management:
      name: http-management
      type: ClusterIP
      port: 15672
  username: admin
    