rabbitmq:
  enabled: true
  image: rabbitmq
  tag: 3.12-management
  replicas: 1
  service:
    type: ClusterIP
    amqp:
      port: 5672
      host: rmq.lriedel.fun
    management:
      port: 15672
      host: rmq.lriedel.fun
  username: admin