{{- define "core.volumeMounts" }}
- name: {{ .Release.Name }}-tmp
  mountPath: /tmp
- name: {{ .Release.Name }}-data
  mountPath: /var/tmp
- name: {{ .Release.Name }}-config
  mountPath: /usr/local/etc/php/conf.d/zz-custom.ini
  subPath: custom.ini
{{- end }}