{{- define "core.volumeMounts" }}
- name: {{ .Release.Name }}-tmp
  mountPath: /tmp
- name: {{ .Release.Name }}-var-tmp
  mountPath: /var/tmp
- name: {{ .Release.Name }}-var-run
  mountPath: /var/run
- name: {{ .Release.Name }}-var-lib-nginx
  mountPath: /var/lib/nginx
- name: {{ .Release.Name }}-var-log-nginx
  mountPath: /var/log/nginx
- name: {{ .Release.Name }}-config
  mountPath: /usr/local/etc/php/conf.d/zz-custom.ini
  subPath: custom.ini
{{- end }}