{{- define "core.volumes" }}
- name: {{ .Release.Name }}-tmp
  emptyDir: {}
- name: {{ .Release.Name }}-data
  persistentVolumeClaim:
    claimName: {{ .Release.Name }}-pvc
- name: {{ .Release.Name }}-config
  configMap:
    name: {{ .Release.Name }}-configmap
{{- end }}