{{- define "core.volumes" }}
- name: {{ .Release.Name }}-tmp
  emptyDir: {}
- name: {{ .Release.Name }}-data
  emptyDir: {}
- name: {{ .Release.Name }}-config
  configMap:
    name: {{ .Release.Name }}-configmap
{{- end }}