{{- if .Values.core.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: core-worker-cronjob
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: core-worker
            image: "{{ .Values.core.image }}:{{ .Values.core.tag }}"
            command: ["php", "-d", "max_execution_time=3600", "-d", "memory_limit=512M", "/var/www/html/src/worker.php"]
            env:
{{ include "core.env" . | nindent 14 }}
            volumeMounts:
{{ include "core.volumeMounts" . | nindent 14 }}
          volumes:
{{ include "core.volumes" . | nindent 12 }}
{{- end }}
