{{- if .Values.core.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.core.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: {{ .Release.Name }}
          resources:
            requests:
              cpu: 200m
              memory: 150Mi
            limits:
              cpu: 1000m
              memory: 2.2G # TODO: Reduce the limit after reworking the deployment script.
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.core.image }}:{{ .Values.core.tag }}"
          ports:
            - containerPort: {{ .Values.core.service.port }}
          readinessProbe:
            httpGet:
              path: /management/readiness
              port: {{ .Values.core.service.port }}
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.core.service.port }}
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.core.service.port }}
            periodSeconds: 10
            failureThreshold: 50
            timeoutSeconds: 5
          env:
{{- include "core.env" . | nindent 12 }}
          volumeMounts:
{{- include "core.volumeMounts" . | nindent 12 }}
      volumes:
{{- include "core.volumes" . | nindent 8 }}
{{- end }}