{{- if .Values.core.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  labels:
    app: core
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: "{{ .Values.core.image }}:{{ .Values.core.tag }}"
          ports:
            - containerPort: {{ .Values.core.service.port }}            
          env:
{{- include "core.env" . | nindent 12 }}
          volumeMounts:
{{- include "core.volumeMounts" . | nindent 12 }}
      volumes:
{{- include "core.volumes" . | nindent 8 }}
{{- end }}