{{- if .Values.core.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-light
  labels:
    app: {{ .Release.Name }}-worker-light
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
        version: "{{ .Values.core.tag }}"
        client: {{ .Values.core.grafana.client.name }}
        logging: "true"
    spec:
      nodeSelector:
        type: light
{{- include "core.podWorker" . | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-heavy
  labels:
    app: {{ .Release.Name }}-worker-heavy
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
        version: "{{ .Values.core.tag }}"
        client: {{ .Values.core.grafana.client.name }}
        logging: "true"
    spec:
      nodeSelector:
        type: heavy
{{- include "core.podWorker" . | nindent 6 }}
{{- end }}