{{- if .Values.core.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-worker-scaler-secret
type: Opaque
stringData:
  rmqConnectionString: "http://{{ .Values.core.rabbitmq.internal.hostname }}.default.svc.cluster.local:{{ .Values.core.rabbitmq.internal.port.management }}/{{ .Values.core.rabbitmq.vhost | trimPrefix "/" | urlquery }}"
  rmqUser: "{{ .Values.core.rabbitmq.username }}"
{{- end }}