{{- if .Values.iam.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-web-router
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.iam.service.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.iam.service.port }}
  tls:
    certResolver: letsencrypt
{{- end }}