services:
  service:
    build: .
    ports:
      - 8080:80
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: main
      PRIVATE_KEY: private_key
      BASE_URL: http://localhost:8080
    depends_on:
      - db
    command: >
      sh -c "wait-for-it db:3306 -s -t 60 && 
      mkdir -p /var/www/html/config && 
      echo '<?php
        define(\"DB_NAME\", getenv(\"DB_NAME\"));
        define(\"DB_USER\", getenv(\"DB_USER\"));
        define(\"DB_PASSWORD\", getenv(\"DB_PASSWORD\"));
        define(\"DB_HOST\", getenv(\"DB_HOST\"));
        define(\"PRIVATE_KEY\", getenv(\"PRIVATE_KEY\"));
        define(\"BASE_URL\", getenv(\"BASE_URL\"));
      ?>' > /var/www/html/config/secrets.php && 
      composer install && 
      php /var/www/html/php/deploy.php && 
      apache2-foreground"
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: main
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db