{{- if .Values.redisinsight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
spec:
  replicas: {{ .Values.redisinsight.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: "{{ .Values.redisinsight.image }}:{{ .Values.redisinsight.tag }}"
          ports:
            - containerPort: {{ .Values.redisinsight.service.port }}
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "{{ .Values.redis.service.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: redis-password
          volumeMounts:
            - name: redisinsight-data
              mountPath: /data
      volumes:
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: redisinsight-pvc
{{- end }}
