{{- if .Values.rediscommander.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rediscommander
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rediscommander
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rediscommander
    spec:
      nodeSelector:
        type: local
      containers:
        - name: {{ .Release.Name }}-rediscommander
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          image: "{{ .Values.rediscommander.image }}:{{ .Values.rediscommander.tag }}"
          ports:
            - containerPort: {{ .Values.rediscommander.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.rediscommander.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.rediscommander.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 1  
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "{{ .Values.redis.service.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: redis-password
{{- end }}
