{{- if .Values.rediscommander.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-rediscommander-web-router
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.rediscommander.service.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-rediscommander
          port: {{ .Values.rediscommander.service.port }}
      middlewares:
        - name: {{ .Release.Name }}-rediscommander-auth-middleware
  tls:
    certResolver: letsencrypt
{{- end }}
