{{- if .Values.rediscommander.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-rediscommander-auth-middleware
spec:
  basicAuth:
    secret: rediscommander-password # TODO: Rename to {{ .Release.Name }}-rediscommander-password
{{- end }}