{{- if .Values.rediscommander.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rediscommander
spec:
  type: {{ .Values.rediscommander.service.type }}
  ports:
    - port: {{ .Values.rediscommander.service.port }}
      targetPort: {{ .Values.rediscommander.service.port }}
  selector:
    app: {{ .Release.Name }}-rediscommander
{{- end }}
