{{- if .Values.redisinsight.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
spec:
  type: {{ .Values.redisinsight.service.type }}
  ports:
    - port: {{ .Values.redisinsight.service.port }}
      targetPort: {{ .Values.redisinsight.service.port }}
  selector:
    app: redisinsight
{{- end }}
