worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    include              mime.types;
    default_type         application/octet-stream;
    sendfile             on;
    client_max_body_size 20M;

    proxy_cache_path /var/tmp/cache/nginx levels=1:2 keys_zone=nginx_cache:8m max_size=1G inactive=1h use_temp_path=off;

    server {
        listen 8080;
        server_name _;

        root /var/www/html/public;

        index index.php;

        location = /swagger {
            try_files /swagger/index.html =404;
        }

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
        }

        location /proxy/googleusercontent/ {
            proxy_pass https://lh3.googleusercontent.com/;
            proxy_set_header Host lh3.googleusercontent.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ignore_headers Cache-Control Expires Set-Cookie;
            proxy_cache nginx_cache;
            proxy_cache_valid 200 1h;
        }
    }
}
