iam:
  enabled: true
  image: ghcr.io/lukas-riedel/iam
  # tag: latest
  replicas: 1
  service:
    type: ClusterIP
    port: 8080
  client:
    app:
      id: travel-portal-app
    backend:
      id: admin-cli
  jwks:
    key:
      public: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkWwmkfjL3R6lTrYpzuc8c6xhEonmJKUll5JNfVgvaMTmi6TfEsmOCJsaJoLy5TVozoCcjGs+01wRr6X93l4dj20Y1dXE8P7SLX9BiPVgbOR7P5oWQxgMQ4pogDaUNY784Y0wtVHkIPN/U+uDzs8IIPDnCLpIkf/P3f8gubB31fD3UkRah2ppifTqUVK3hI1/fFCxKCsegwJu1rqoUAypehf7uLGKMfZpcZsLYwaLc2WnvVf7kEqrCtr1jhGt8oUcjYX+hje3y6hPhPNpBPaRsjqT+C/RZGaCSImwA5zIc//G/Q5aYqiD72rHa3tbFTAo/j+/fhOpKGnKq4oBqYUBXQIDAQAB\n-----END PUBLIC KEY-----\n
  url:
    base:
      public: https://iam.lriedel.fun
      private:
        user: https://lemur-9.cloud-iam.com/auth/realms/travel-portal
        admin: https://lemur-9.cloud-iam.com/auth/admin/realms/travel-portal
  fcm:
    project:
      id: travel-blog-free
    client:
      id: 109261228732220758403
      email: firebase-adminsdk-fbsvc@travel-blog-free.iam.gserviceaccount.com
      certificate:
        url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40travel-blog-free.iam.gserviceaccount.com
  google:
    client:
      id: 260891677871-n02h7nhapeelp4jkkgejsj5m54ramkoq.apps.googleusercontent.com
  grafana:
    entrypoint: https://logs-prod-012.grafana.net
    client:
      name: travel-portal-service
    username: 1287508
  origins:
    whitelist: https://travel-portal.eu,https://lriedel.cz