postgres:
  enabled: true
  image: garapadev/postgres-postgis-pgvector
  tag: 16-slim
  replicas: 1
  database: core
  service:
    type: ClusterIP
    port: 5432
pgadmin:
  enabled: true
  image: dpage/pgadmin4
  tag: latest
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    host: postgres.lriedel.cz
