{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image }}:{{ .Values.minio.tag }}"
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.minio.service.console.port }}"
          ports:
            - name: s3
              containerPort: {{ .Values.minio.service.s3.port }}
            - name: http-console
              containerPort: {{ .Values.minio.service.console.port }}
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.minio.username }}"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-password
                  key: minio-password
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "https://{{ .Values.minio.service.console.host }}"
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
{{- end }}