
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  type: {{ .Values.minio.service.s3.type }}   
  ports:
    - port: {{ .Values.minio.service.s3.port }}
      targetPort: {{ .Values.minio.service.s3.port }}
      protocol: TCP
      name: s3
    - port: {{ .Values.minio.service.console.port }}
      targetPort: {{ .Values.minio.service.console.port }}
      protocol: TCP
      name: http-console
  selector:
    app: minio
{{- end }}