{{- if .Values.cortex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.cortex.replicas }}
  strategy:
    type: Recreate # Switch to RollingUpdate after upgrading the memory.
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: "{{ .Values.cortex.tag }}"
        client: {{ .Values.cortex.grafana.client.name }}
        logging: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Release.Name }}
          resources:
            requests:
              cpu: 100m
              memory: 1300Mi
            limits:
              cpu: 3000m
              memory: 4Gi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.cortex.image }}:{{ .Values.cortex.tag }}"
          ports:
            - containerPort: {{ .Values.cortex.service.port }}
          readinessProbe:
            httpGet:
              path: /management/readiness
              port: {{ .Values.cortex.service.port }}
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.cortex.service.port }}
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.cortex.service.port }}
            periodSeconds: 10
            failureThreshold: 50
            timeoutSeconds: 5
          env:
            - name: VERSION_TAG
              value: "{{ .Values.cortex.tag }}"
            - name: APP_NAME
              value: "{{ .Release.Name }}"
            - name: WORKERS_COUNT
              value: "{{ .Values.cortex.workers }}"
            - name: EMBEDDINGS_MODEL_NAME
              value: "{{ .Values.cortex.model.embeddings }}"
            - name: TRANSLATION_MODEL_NAME_FORMAT
              value: "{{ .Values.cortex.model.translation }}"
            - name: ENGINE_DEVICE
              value: "{{ .Values.cortex.engine }}"
            - name: IAM_HOST
              value: "{{ .Values.cortex.iam.host }}"
            - name: IAM_PORT
              value: "{{ .Values.cortex.iam.port }}"
            - name: IAM_APP_CLIENT_ID
              value: "{{ .Values.cortex.iam.client.app.id }}"
            - name: IAM_BACKEND_CLIENT_ID
              value: "{{ .Values.cortex.iam.client.backend.id }}"
            - name: SUPPORTED_LANGUAGES
              value: "{{ .Values.cortex.languages }}"
          volumeMounts:
            - name: {{ .Release.Name }}-tmp
              mountPath: /tmp
            - name: {{ .Release.Name }}-home-appuser
              mountPath: /home/appuser
      volumes:
        - name: {{ .Release.Name }}-tmp
          emptyDir: {}
        - name: {{ .Release.Name }}-home-appuser
          emptyDir: {}
{{- end }}
