{{- if .Values.cortex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-worker
  labels:
    app: cortex-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cortex-worker
  template:
    metadata:
      labels:
        app: cortex-worker
    spec:
      terminationGracePeriodSeconds: {{ .Values.cortex.scaling.grace }}
      containers:
        - name: cortex-worker
          image: "{{ .Values.cortex.image }}:{{ .Values.cortex.tag }}"
          env:
            - name: VERSION_TAG
              value: "{{ .Values.cortex.tag }}"
            - name: MAX_THREADS
              value: "{{ .Values.cortex.threads }}"
            - name: MODEL_NAME
              value: "{{ .Values.cortex.model }}"
            - name: ENGINE_DEVICE
              value: "{{ .Values.cortex.engine }}"
            - name: CONTENT_COEFFICIENT
              value: "{{ .Values.cortex.highlights.coefficient.content }}"
            - name: NEGATIVE_COEFFICIENT
              value: "{{ .Values.cortex.highlights.coefficient.negative }}"
            - name: AGE_COEFFICIENT
              value: "{{ .Values.cortex.highlights.coefficient.age }}"
            - name: SIMILARITY_THRESHOLD
              value: "{{ .Values.cortex.highlights.threshold.similarity }}"
            - name: CORE_BASE_URL
              value: "{{ .Values.cortex.url.core.base.public }}"
            - name: IAM_BASE_URL
              value: "{{ .Values.cortex.url.iam.base.public }}"
            - name: RMQ_HOST
              value: "{{ .Values.cortex.rabbitmq.hostname }}"            
            - name: RMQ_PORT
              value: "{{ .Values.cortex.rabbitmq.port.amqp }}"
            - name: RMQ_VHOST
              value: "{{ .Values.cortex.rabbitmq.vhost }}"  
            - name: RMQ_USER
              value: "{{ .Values.cortex.rabbitmq.username }}"
            - name: RMQ_HEARTBEAT
              value: "{{ .Values.cortex.rabbitmq.heartbeat }}"
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password
                  key: rabbitmq-password
            - name: CORTEX_QUEUE_NAME
              value: "{{ .Values.cortex.rabbitmq.queue.cortex }}"
            - name: REDIS_HOST
              value: "{{ .Values.cortex.redis.hostname }}"            
            - name: REDIS_PORT
              value: "{{ .Values.cortex.redis.port }}"  
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: redis-password
            - name: IAM_BACKEND_CLIENT_ID
              value: "{{ .Values.cortex.iam.client.backend.id }}"
            - name: IAM_BACKEND_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: iam-client-backend-secret
                  key: iam-client-backend-secret
            - name: GRAFANA_LOKI_ENTRYPOINT
              value: "{{ .Values.cortex.grafana.entrypoint }}"
            - name: GRAFANA_LOKI_CLIENT_NAME
              value: "{{ .Values.cortex.grafana.client.name }}"
            - name: GRAFANA_LOKI_USER
              value: "{{ .Values.cortex.grafana.username }}"
            - name: GRAFANA_LOKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-password
                  key: grafana-password
{{- end }}
