{{- if .Values.cortex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.cortex.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.cortex.image }}:{{ .Values.cortex.tag }}"
          ports:
            - containerPort: {{ .Values.cortex.service.port }}
          readinessProbe:
            httpGet:
              path: /management/readiness
              port: {{ .Values.cortex.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.cortex.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.cortex.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 3
          env:
            - name: VERSION_TAG
              value: "{{ .Values.cortex.tag }}"
            - name: APP_NAME
              value: "{{ .Release.Name }}"
            - name: WORKERS_COUNT
              value: "{{ .Values.cortex.workers }}"
            - name: MODEL_NAME
              value: "{{ .Values.cortex.model }}"
            - name: ENGINE_DEVICE
              value: "{{ .Values.cortex.engine }}"
            - name: IAM_HOST
              value: "{{ .Values.cortex.iam.host }}"
            - name: IAM_PORT
              value: "{{ .Values.cortex.iam.port }}"
            - name: IAM_APP_CLIENT_ID
              value: "{{ .Values.cortex.iam.client.app.id }}"
            - name: IAM_BACKEND_CLIENT_ID
              value: "{{ .Values.cortex.iam.client.backend.id }}"
            - name: GRAFANA_LOKI_ENTRYPOINT
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-entrypoint
            - name: GRAFANA_LOKI_CLIENT_NAME
              value: "{{ .Values.cortex.grafana.client.name }}"
            - name: GRAFANA_LOKI_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-username
            - name: GRAFANA_LOKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-password
            - name: SUPPORTED_LANGUAGES
              value: "{{ .Values.cortex.languages }}"
          volumeMounts:
            - name: {{ .Release.Name }}-tmp
              mountPath: /tmp
            - name: {{ .Release.Name }}-home-appuser
              mountPath: /home/appuser
      volumes:
        - name: {{ .Release.Name }}-tmp
          emptyDir: {}
        - name: {{ .Release.Name }}-home-appuser
          emptyDir: {}
{{- end }}
