{{- if .Values.cortex.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-worker-scaler
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-worker
  minReplicaCount: 0
  maxReplicaCount: {{ .Values.cortex.workers }}
  pollingInterval: 15
  cooldownPeriod: {{ .Values.cortex.scaling.cooldown }}
  triggers:
    - type: rabbitmq
      metadata:
        mode: QueueLength
        value: "{{ .Values.cortex.scaling.items }}"
        queueName: "{{ .Values.cortex.rabbitmq.queue.cortex }}"
      authenticationRef:
        name: {{ .Release.Name }}-worker-scaler-auth
{{- end }}