{{- if .Values.cortex.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cortex-worker-scaler-secret
type: Opaque
stringData:
  rmqConnectionString: "http://{{ .Values.cortex.rabbitmq.hostname }}.default.svc.cluster.local:{{ .Values.cortex.rabbitmq.port.management }}/{{ .Values.cortex.rabbitmq.vhost | trimPrefix "/" | urlquery }}"
  rmqUser: "{{ .Values.cortex.rabbitmq.username }}"
{{- end }}