{{- if .Values.opensearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.opensearch.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: set-vm-max-map-count
          image: busybox
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.opensearch.image }}:{{ .Values.opensearch.tag }}"
          ports:
            - containerPort: {{ .Values.opensearch.service.port }}
          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: {{ .Values.opensearch.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: {{ .Values.opensearch.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: cluster.name
              value: {{ .Release.Name }}
            - name: discovery.type
              value: "single-node"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: bootstrap.memory_lock
              value: "false"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
{{- end }}