portal:
  enabled: true
  image: ghcr.io/lukas-riedel/portal
  # tag: latest
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    host: lriedel.fun
  url:
    base:
      public: https://lriedel.fun
    iam:
      base:
        public: https://iam.lriedel.fun
    core:
      base:
        public: https://api.lriedel.fun
  iam:
    client:
      app:
        id: travel-portal-app
  fcm:
    key:
      api: AIzaSyDHE5OQxnc9H3MDYvKh_XMDII2aGl1WGbY
      vapid: BB3b84HrUo70xfMK0D6XU6m_akT5LVYUPLPyVsx4jB2RwLNLWzFsQrNB1X_SQygIqF5lQASHXDW13ysSOlGNqZI
    domain:
      auth: travel-blog-free.firebaseapp.com
    project:
      id: travel-blog-free
    bucket:
      storage: travel-blog-free.firebasestorage.app
    messaging:
      sender:
        id: "917611440173"
    app:
      id: 1:917611440173:web:61960e323dd4e730acb0a4
    measurement:
      id: G-TQC1X1T5X2
  google:
    maps:
      key:
        api: AIzaSyDRmOGaKnOreWBiOeKwfrb5I2qnmff4Su0