portal:
  enabled: true
  service:
    host: travel-portal.eu
  credentials:
    default:
      username: light
      password: light
  url:
    base:
      public: https://travel-portal.eu
  content:
    range:
      max: 0