redis:
  enabled: true
  image: redis
  tag: 7.4
  replicas: 1
  service:
    type: ClusterIP
    port: 6379
redisinsight:
  enabled: true
  image: redis/redisinsight
  tag: latest
  replicas: 1
  service:
    type: ClusterIP
    port: 5540
    