{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE EXTENSION IF NOT EXISTS vector;
  postgresql.conf: |
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    shared_buffers = 256MB
    work_mem = 8MB
    temp_buffers = 16MB
    wal_buffers = 8MB
    effective_cache_size = 512MB
    max_connections = 50
    max_parallel_workers = 2
    max_parallel_workers_per_gather = 2
    listen_addresses = '*'
{{- end }}