{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgadmin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgadmin
    spec:
      containers:
        - name: {{ .Release.Name }}-pgadmin
          image: "{{ .Values.pgadmin.image }}:{{ .Values.pgadmin.tag }}"
          ports:
            - containerPort: {{ .Values.pgadmin.service.port }}             
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: {{ .Values.pgadmin.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: {{ .Values.pgadmin.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 1         
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.pgadmin.email }}
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-password # TODO: Change to {{ .Release.Name }}-pgadmin-password
                  key: pgadmin-password
          volumeMounts:
            - name: {{ .Release.Name }}-pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: {{ .Release.Name }}-pgadmin-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pgadmin-pvc
{{- end }}
