{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          command: ["/usr/local/bin/docker-entrypoint.sh"]
          args:
            - "-D"
            - "/var/lib/postgresql/data"
            - "-c"
            - "config_file=/etc/postgresql/custom/postgresql.conf" 
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
                - -d
                - {{ .Values.postgres.database }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
                - -d
                - {{ .Values.postgres.database }}
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: postgres-password
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /var/lib/postgresql/data
            - name: {{ .Release.Name }}-init
              mountPath: /docker-entrypoint-initdb.d
            - name: {{ .Release.Name }}-config
              mountPath: /etc/postgresql/custom/
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: {{ .Release.Name }}-init
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-configmap
{{- end }}