{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: {{ .Values.postgres.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          command: ["/usr/local/bin/docker-entrypoint.sh"]
          args:
            - "-D"
            - "/var/lib/postgresql/data"
            - "-c"
            - "config_file=/etc/postgresql/custom/postgresql.conf" 
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
                - -d
                - {{ .Values.postgres.database }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
                - -d
                - {{ .Values.postgres.database }}
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-config
              mountPath: /etc/postgresql/custom/
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init
          configMap:
            name: postgres-configmap
        - name: postgres-config
          configMap:
            name: postgres-configmap
{{- end }}