{{- if .Values.pgadmin.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-web-router
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.pgadmin.host }}`)
      kind: Rule
      services:
        - name: pgadmin
          port: {{ .Values.pgadmin.service.port }}
  tls:
    certResolver: letsencrypt
{{- end }}
