{{- if .Values.portal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
spec:
  replicas: {{ .Values.portal.replicas }}
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: "{{ .Values.portal.image }}:{{ .Values.portal.tag }}" 
          ports:
            - containerPort: {{ .Values.portal.service.port }}            
          volumeMounts:
            - name: portal-config
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
      volumes:
        - name: portal-config
          configMap:
            name: portal-configmap
{{- end }}