{{- if .Values.portal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.portal.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: {{ .Release.Name }}
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 150Mi
          image: "{{ .Values.portal.image }}:{{ .Values.portal.tag }}" 
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: {{ .Values.portal.service.port }}    
          readinessProbe:
            httpGet:
              path: /management/readiness
              port: {{ .Values.portal.service.port }}
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.portal.service.port }}
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /management/liveness
              port: {{ .Values.portal.service.port }}
            periodSeconds: 10
            failureThreshold: 50
            timeoutSeconds: 5
          volumeMounts:
            - name: {{ .Release.Name }}-config
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
            - name: {{ .Release.Name }}-var-run
              mountPath: /var/run
            - name: {{ .Release.Name }}-var-cache-nginx
              mountPath: /var/cache/nginx
            - name: {{ .Release.Name }}-tmp
              mountPath: /tmp
      volumes:
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: {{ .Release.Name }}-var-run
          emptyDir: {}
        - name: {{ .Release.Name }}-var-cache-nginx
          emptyDir: {}
        - name: {{ .Release.Name }}-tmp
          emptyDir: {}
{{- end }}