{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
        type: cloud
      containers:
        - name: {{ .Release.Name }}
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          image: "{{ .Values.rabbitmq.image }}:{{ .Values.rabbitmq.tag }}"
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.service.amqp.port }}
            - name: http-management
              containerPort: {{ .Values.rabbitmq.service.management.port }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.rabbitmq.service.prometheus.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: {{ .Values.rabbitmq.service.amqp.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: rabbitmq-password 
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /var/lib/rabbitmq/mnesia
            - name: {{ .Release.Name }}-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-config
      hostname: rmq-host
{{- end }}