{{- if .Values.rabbitmq.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rabbitmq-amqp-router
spec:
  entryPoints:
    - amqp
  routes:
    - match: HostSNI(`{{ .Values.rabbitmq.host }}`)
      services:
        - name: rabbitmq
          port: {{ .Values.rabbitmq.service.amqp.port }}
  tls:
    certResolver: letsencrypt
{{- end }}
