{{- if .Values.rabbitmq.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rabbitmq-web-router
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.rabbitmq.host }}`)
      kind: Rule
      services:
        - name: rabbitmq
          port: {{ .Values.rabbitmq.service.management.port }}
  tls:
    certResolver: letsencrypt
{{- end }}