
{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.amqp.type }}   
  ports:
    - port: {{ .Values.rabbitmq.service.amqp.port }}
      targetPort: {{ .Values.rabbitmq.service.amqp.port }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.service.management.port }}
      targetPort: {{ .Values.rabbitmq.service.management.port }}
      protocol: TCP
      name: http-management
  selector:
    app: rabbitmq
{{- end }}