DROP FUNCTION GET_USED_TIME_OFF_FOR_YEAR;
CREATE FUNCTION GET_USED_TIME_OFF_FOR_YEAR(year INT) RETURNS double
    READS SQL DATA
    DETERMINISTIC
RETURN COALESCE(IF(YEAR(CURDATE()) <> year, NULL, (SELECT (-1) * SUM(hours) FROM tracking WHERE type <> 'OVERTIME' AND hours < 0 AND YEAR(FROM_UNIXTIME(timestamp)) = year)), 0);