ALTER TABLE tracking 
MODIFY COLUMN type ENUM('VACATION','SELFCARE','TENURE','OVERTIME','PLANNED_WORK') NOT NULL;

INSERT INTO pruner (`name`, `query`) VALUES ('PRUNE_PLANNED_WORK', 'DELETE FROM tracking WHERE timestamp <= UNIX_TIMESTAMP() AND type = ''PLANNED_WORK''')