rabbitmq:
  enabled: true
  host: rmq.lriedel.fun
  service:
    amqp:
      name: rabbitmq
      port: 5672
    management:
      name: rabbitmq
      port: 15672
redisinsight:
  enabled: true
  host: redis.lriedel.fun
  service:
    name: redisinsight
    port: 5540
pgadmin:
  enabled: true
  host: postgres.lriedel.fun
  service:
    name: pgadmin
    port: 80
iam:
  enabled: true
  host: iam.lriedel.fun
  service:
    name: iam
    port: 8080