on: push
name: Main Pipeline
jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.filter.outputs.core }}
      portal: ${{ steps.filter.outputs.portal }}
      agent: ${{ steps.filter.outputs.agent }}
      bridgex: ${{ steps.filter.outputs.bridgex }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4    
      - name: Filter Paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'Core/**'
            portal:
              - 'Portal/**'
            agent:
              - 'Agent/**'
            bridgex:
              - 'BridgeX/**'
  deploy-core-and-portal:
    name: Deploy Core and Portal
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.core == 'true' || needs.detect-changes.outputs.portal == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    - name: Set Up PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, mysqli
        coverage: none
    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '18'
    - name: Install Composer Dependencies
      run: |
        cd Core
        composer install --no-dev --optimize-autoloader
    - name: Install NPM Dependencies
      run: |
        cd Portal
        npm install --legacy-peer-deps
    - name: Build React Project
      run: |
        cd Portal
        npm run build
      env:
        VITE_SW_VERSION: ${{ github.run_number }}
        VITE_PORTAL_BASE_URL: ${{ vars.PORTAL_BASE_URL }}
        VITE_CORE_BASE_URL: ${{ vars.CORE_BASE_URL }}
        VITE_IAM_BASE_URL: ${{ vars.IAM_BASE_URL }}
        VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
        VITE_FIREBASE_MEASUREMENT_ID: ${{ vars.FIREBASE_MEASUREMENT_ID }}
        VITE_FIREBASE_VAPID_KEY: ${{ secrets.FIREBASE_VAPID_KEY }}
    - name: Prepare Files
      run: |
        mkdir target
        mkdir target/api
        shopt -s dotglob
        cp -r ./Core/* target/api/
        rm -rf target/api/public
        cp -r ./Core/public/* target/api/
        cp -r ./Portal/dist/* target/
    - name: Upload Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ vars.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: target/
        server-dir: ${{ vars.FTP_DIRECTORY }}
    - name: Deploy
      uses: muhfaris/request-action@v0.1.2
      with:
        method: GET
        url: ${{ vars.CORE_BASE_URL }}/deploy.php
  verify-agent:
    name: Verify Agent
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.agent == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify
        run: mvn verify -f Agent/pom.xml
  deploy-bridgex-android:
    name: Deploy BridgeX Android
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.bridgex == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4