on: push
name: Main Pipeline
jobs:
  web-deploy:
    name: Deploy Web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    - name: Upload Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 254146.w46.wedos.net
        username: w254146
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./Web/
        server-dir: www/domains/lriedel.cz/
    - name: Migrate Database
      uses: muhfaris/request-action@v0.1.2
      with:
        url: https://lriedel.cz/php/deploy.php?backupDatabase=true
        method: GET
  maven-verify:
    name: Build Photo Uploader
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Verification
        run: mvn verify -f PhotoUploader/pom.xml