cortex:
  enabled: true
  image: ghcr.io/lukas-riedel/cortex
  tag: latest
  replicas: 1
  workers: 1
  service:
    type: ClusterIP
    port: 8080
  model: clip-ViT-L-14
  engine: cpu
  iam:
    host: iam
    port: 8080
    client:
      app:
        id: travel-portal-app
      backend:
        id: admin-cli
  grafana:
    client:
      name: travel-portal-service
  languages: cs,en