cortex:
  enabled: true
  image: ghcr.io/lukas-riedel/cortex
  tag: latest
  replicas: 2
  workers: 2
  service:
    type: ClusterIP
    port: 8080
  model:
    embeddings: clip-ViT-L-14
    generative:
      - models/gemini-3.5-flash-lite
      - models/gemini-3.5-flash
      - models/gemini-3.6-flash
      - models/gemini-3.1-flash-lite
      - models/gemini-3.8-flash
      - models/gemini-2.5-flash-lite
      - models/gemini-2.5-flash
      - models/gemini-3-flash
  engine: cpu
  iam:
    host: iam
    port: 8080
    client:
      backend:
        id: admin-cli
  core:
    host: core
    port: 8080
  grafana:
    client:
      name: travel-portal-service