cortex:
  enabled: true
  image: ghcr.io/lukas-riedel/cortex
  tag: latest
  replicas: 2
  workers: 2
  service:
    type: ClusterIP
    port: 8080
  model:
    embeddings: clip-ViT-L-14
  engine: cpu
  iam:
    host: iam
    port: 8080
    client:
      app:
        id: travel-portal-app
      backend:
        id: admin-cli
  grafana:
    client:
      name: travel-portal-service